import type { RunConfig } from './types';

export const DEFAULT_CONFIG: RunConfig = {
  N: 30,
  K: 4,
  diffuse_threshold: 0.6,
  direct_k: 2,
  level_sigma: 0.8,
  reinterpret_alpha: 1.0,
  ai_delegate_threshold_mode: 'per_agent',
  ai_delegate_threshold_default: 2,
  ai_reply_beta: 0.5,
  delta_reply_human: 0.03,
  delta_reply_ai: 0.01,
  delta_ignore_human: 0.04,
  delta_spam: 0.01,
  steps: 300,
  messages_per_step_mean: 1.2,
  weak_tie_threshold: 0.35,
  prune_ignore_count_threshold: 2,
  prune_window_steps: 50,
  bond_decay: 0.999,
  w_perceived_reply: 0.02,
  w_real_reply_human: 0.02,
  w_real_reply_ai: 0.002,
  w_bond_human: 0.03,
  w_bond_ai: 0.003,
  w_ignore: 0.03,
  w_delegate_direct: -0.01,
  w_delegate_broadcast: 0.01,
  w_delegate_prune: 0.01,
  w_delegate_perceived: 0.005,
};
